### PR TITLE
Polyline drawing

### PR DESCRIPTION
**Pull request by firesharker**
I like to visualize trajectories with lines, but I think I am not alone with this.

figure 1_screenshot_28 05 2018

### CODE REVIEW

**Comment by nwojke** [comment]
Funny, I comitted a function called [line_strip](https://github.com/nwojke/pymotutils/blob/master/pymotutils/visualization/opencv.py#L253) just around the same time. Your code looks more advanced, though. I'll remove the line_strip and merge this one.

**Comment by nwojke** [comment]
@firesharker Did you make changes to [draw_track_set](https://github.com/nwojke/pymotutils/pull/5/files#diff-3f4a57613a1bbc710e9da3c76bdc4a01L133) in order to generate the image? If so, we could add an attribute ``draw_trajectories``, or better ``trajectory_visualization_len`` to the class in order to control whether a history of past times should be drawn.

**Comment by firesharker** [comment]
Yes, I here it is:
```python
def draw_track_set(self, frame_idx, track_set):
    track_set_frame = track_set.collect_sensor_data(frame_idx)

    self._viewer.thickness = self.track_set_thickness
    if self.draw_trajectories:
        for tag in track_set_frame.keys():
            self._viewer.color = pymotutils.create_unique_color_uchar(tag)
            track = track_set.tracks[tag]
            points = []
            for this_frame_idx in range(track.first_frame_idx(), frame_idx):
                if this_frame_idx not in track.detections:
                    continue
                x, y, w, h = track.detections[this_frame_idx].sensor_data
                x, y = int(x + w / 2), int(y + h)
                points.append([x, y])
                self._viewer.circle(x, y, 1)
            if len(points) > 0:
                points = np.asarray(points)
                self._viewer.thickness = 10
                self._viewer.polyline(points, alpha=0.5)
                self._viewer.thickness = self.track_set_thickness
    for tag, (x, y, w, h) in track_set_frame.items():
        self._viewer.color = pymotutils.create_unique_color_uchar(tag)
        self._viewer.rectangle(x, y, w, h, label=str(tag))
```
I agree, `trajectory_visualization_len` would be a great addition. Usually I slice the last n points to avoid long tracks cluttering the image.

**Comment by nwojke** [comment]
Ok, let's try to get this functionality into the library. If you find the time before me, you can modify the PR, otherwise I'll try to take care of it.

**Comment by nwojke** [comment]
I am a bit slow with project maintenance, but now it is merged. In a follow-up commit https://github.com/nwojke/pymotutils/commit/e702a76f552b641d50bab7d3ee48292650796d49 I have removed the line_strip function in favor of polyline. The motchallenge example has been changed to visualize 3 seconds of the ground truth trajectory in https://github.com/nwojke/pymotutils/commit/3cebd83b41c7f8db145a39aead5a2eeac79debec.

Thanks for the contribution!

**Pull request merged**
